// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: proto/control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Control_ConnectClient, error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Control_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[0], "/gorhino.control.v1.Control/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlConnectClient{stream}
	return x, nil
}

type Control_ConnectClient interface {
	Send(*WorkerMsg) error
	Recv() (*MasterMsg, error)
	grpc.ClientStream
}

type controlConnectClient struct {
	grpc.ClientStream
}

func (x *controlConnectClient) Send(m *WorkerMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controlConnectClient) Recv() (*MasterMsg, error) {
	m := new(MasterMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility
type ControlServer interface {
	Connect(Control_ConnectServer) error
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have forward compatible implementations.
type UnimplementedControlServer struct {
}

func (UnimplementedControlServer) Connect(Control_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServer).Connect(&controlConnectServer{stream})
}

type Control_ConnectServer interface {
	Send(*MasterMsg) error
	Recv() (*WorkerMsg, error)
	grpc.ServerStream
}

type controlConnectServer struct {
	grpc.ServerStream
}

func (x *controlConnectServer) Send(m *MasterMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controlConnectServer) Recv() (*WorkerMsg, error) {
	m := new(WorkerMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gorhino.control.v1.Control",
	HandlerType: (*ControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Control_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/control.proto",
}
